# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_pb2 as grpc__pb2


class UITransferStub(object):
    """todo: map in proto is not ordered. Perhaps switch to 2 repeated fields?
    or alternatively we can provide an order object somewhere
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.buy = channel.unary_unary(
                '/plushie_tycoon.UITransfer/buy',
                request_serializer=grpc__pb2.TransactionObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.sell = channel.unary_unary(
                '/plushie_tycoon.UITransfer/sell',
                request_serializer=grpc__pb2.TransactionObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.make = channel.unary_unary(
                '/plushie_tycoon.UITransfer/make',
                request_serializer=grpc__pb2.TransactionObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.next = channel.unary_unary(
                '/plushie_tycoon.UITransfer/next',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.save = channel.unary_unary(
                '/plushie_tycoon.UITransfer/save',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.load = channel.unary_unary(
                '/plushie_tycoon.UITransfer/load',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.back = channel.unary_unary(
                '/plushie_tycoon.UITransfer/back',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.quit = channel.unary_unary(
                '/plushie_tycoon.UITransfer/quit',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.init = channel.unary_unary(
                '/plushie_tycoon.UITransfer/init',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )


class UITransferServicer(object):
    """todo: map in proto is not ordered. Perhaps switch to 2 repeated fields?
    or alternatively we can provide an order object somewhere
    """

    def buy(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sell(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def make(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def next(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def back(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def quit(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def init(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UITransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'buy': grpc.unary_unary_rpc_method_handler(
                    servicer.buy,
                    request_deserializer=grpc__pb2.TransactionObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'sell': grpc.unary_unary_rpc_method_handler(
                    servicer.sell,
                    request_deserializer=grpc__pb2.TransactionObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'make': grpc.unary_unary_rpc_method_handler(
                    servicer.make,
                    request_deserializer=grpc__pb2.TransactionObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'next': grpc.unary_unary_rpc_method_handler(
                    servicer.next,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'load': grpc.unary_unary_rpc_method_handler(
                    servicer.load,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'back': grpc.unary_unary_rpc_method_handler(
                    servicer.back,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'quit': grpc.unary_unary_rpc_method_handler(
                    servicer.quit,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plushie_tycoon.UITransfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UITransfer(object):
    """todo: map in proto is not ordered. Perhaps switch to 2 repeated fields?
    or alternatively we can provide an order object somewhere
    """

    @staticmethod
    def buy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/buy',
            grpc__pb2.TransactionObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/sell',
            grpc__pb2.TransactionObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def make(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/make',
            grpc__pb2.TransactionObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def next(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/next',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/save',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/load',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def back(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/back',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def quit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/quit',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.UITransfer/init',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class SendCallsStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/plushie_tycoon.SendCalls/register',
                request_serializer=grpc__pb2.UserID.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.isregistered = channel.unary_unary(
                '/plushie_tycoon.SendCalls/isregistered',
                request_serializer=grpc__pb2.UserID.SerializeToString,
                response_deserializer=grpc__pb2.ReturnCode.FromString,
                )
        self.send = channel.unary_unary(
                '/plushie_tycoon.SendCalls/send',
                request_serializer=grpc__pb2.ProposedChanges.SerializeToString,
                response_deserializer=grpc__pb2.ReturnCode.FromString,
                )
        self.query = channel.unary_unary(
                '/plushie_tycoon.SendCalls/query',
                request_serializer=grpc__pb2.UserID.SerializeToString,
                response_deserializer=grpc__pb2.Snapshot.FromString,
                )
        self.getTime = channel.unary_unary(
                '/plushie_tycoon.SendCalls/getTime',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.IntObject.FromString,
                )
        self.hasUpdated = channel.unary_unary(
                '/plushie_tycoon.SendCalls/hasUpdated',
                request_serializer=grpc__pb2.UserID.SerializeToString,
                response_deserializer=grpc__pb2.ReturnCode.FromString,
                )


class SendCallsServicer(object):
    """Missing associated documentation comment in .proto file"""

    def register(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isregistered(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def query(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTime(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def hasUpdated(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendCallsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=grpc__pb2.UserID.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'isregistered': grpc.unary_unary_rpc_method_handler(
                    servicer.isregistered,
                    request_deserializer=grpc__pb2.UserID.FromString,
                    response_serializer=grpc__pb2.ReturnCode.SerializeToString,
            ),
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=grpc__pb2.ProposedChanges.FromString,
                    response_serializer=grpc__pb2.ReturnCode.SerializeToString,
            ),
            'query': grpc.unary_unary_rpc_method_handler(
                    servicer.query,
                    request_deserializer=grpc__pb2.UserID.FromString,
                    response_serializer=grpc__pb2.Snapshot.SerializeToString,
            ),
            'getTime': grpc.unary_unary_rpc_method_handler(
                    servicer.getTime,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.IntObject.SerializeToString,
            ),
            'hasUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.hasUpdated,
                    request_deserializer=grpc__pb2.UserID.FromString,
                    response_serializer=grpc__pb2.ReturnCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plushie_tycoon.SendCalls', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SendCalls(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.SendCalls/register',
            grpc__pb2.UserID.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def isregistered(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.SendCalls/isregistered',
            grpc__pb2.UserID.SerializeToString,
            grpc__pb2.ReturnCode.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.SendCalls/send',
            grpc__pb2.ProposedChanges.SerializeToString,
            grpc__pb2.ReturnCode.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.SendCalls/query',
            grpc__pb2.UserID.SerializeToString,
            grpc__pb2.Snapshot.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.SendCalls/getTime',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.IntObject.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def hasUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.SendCalls/hasUpdated',
            grpc__pb2.UserID.SerializeToString,
            grpc__pb2.ReturnCode.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class AdminSendStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendCall = channel.unary_unary(
                '/plushie_tycoon.AdminSend/sendCall',
                request_serializer=grpc__pb2.ProposedChanges.SerializeToString,
                response_deserializer=grpc__pb2.NullObject.FromString,
                )


class AdminSendServicer(object):
    """Missing associated documentation comment in .proto file"""

    def sendCall(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminSendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendCall': grpc.unary_unary_rpc_method_handler(
                    servicer.sendCall,
                    request_deserializer=grpc__pb2.ProposedChanges.FromString,
                    response_serializer=grpc__pb2.NullObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plushie_tycoon.AdminSend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminSend(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def sendCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.AdminSend/sendCall',
            grpc__pb2.ProposedChanges.SerializeToString,
            grpc__pb2.NullObject.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class AdminReturnStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.nextTurn = channel.unary_unary(
                '/plushie_tycoon.AdminReturn/nextTurn',
                request_serializer=grpc__pb2.NullObject.SerializeToString,
                response_deserializer=grpc__pb2.NullObject.FromString,
                )


class AdminReturnServicer(object):
    """Missing associated documentation comment in .proto file"""

    def nextTurn(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminReturnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'nextTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.nextTurn,
                    request_deserializer=grpc__pb2.NullObject.FromString,
                    response_serializer=grpc__pb2.NullObject.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plushie_tycoon.AdminReturn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminReturn(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def nextTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.AdminReturn/nextTurn',
            grpc__pb2.NullObject.SerializeToString,
            grpc__pb2.NullObject.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class TestCallStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.callthis = channel.unary_unary(
                '/plushie_tycoon.TestCall/callthis',
                request_serializer=grpc__pb2.IntObject.SerializeToString,
                response_deserializer=grpc__pb2.ReturnCode.FromString,
                )


class TestCallServicer(object):
    """Missing associated documentation comment in .proto file"""

    def callthis(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestCallServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'callthis': grpc.unary_unary_rpc_method_handler(
                    servicer.callthis,
                    request_deserializer=grpc__pb2.IntObject.FromString,
                    response_serializer=grpc__pb2.ReturnCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plushie_tycoon.TestCall', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestCall(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def callthis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/plushie_tycoon.TestCall/callthis',
            grpc__pb2.IntObject.SerializeToString,
            grpc__pb2.ReturnCode.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
